### PR TITLE
update address of goerli dmap in view

### PR DESCRIPTION
**Pull request by stobiewan**

### CODE REVIEW

**Comment by sambacha** [comment]
The updated address isn't checksummed fyi.

**Comment by nmushegian** [comment]
@sambacha I already banned you from multiple channels for wasting our time with bullshit. Apparently we are not the only project either. Stop forcing your way into a place you have made yourself unwelcome.

**Comment by nmushegian** [comment]
@sambacha I reported you to github, if you comment again it will be a pattern and you will probably lose your account 
I think we are also taking this repo private ahead of launch, if you want to do some attention seeker nonsense after launch feel free to squat all the best names but leave alone while we are making this

**Comment by nmushegian** [comment]
Will merge separately

**Pull request closed without merging**
